#+title: Car Camping in Urbana-Champaign
#+subtitle: Lessons learned from 2 weeks living out of a Honda HR-V

*TLDR: Being homeless sucks, and while car-living may not seem "that bad", it definitely can be.*

In my college town(s), Urbana-Champaign, almost all leases have a 2-week gap for turnover, right before the start of the semester. 
This means that anyone looking to move is out of housing for 2 weeks. Standard procedure is to go home or stay with a friend who isn't switching apartments if you need to be on campus, but this year, I wanted to try something different: living out of my car.

I've actually been curious about car living for a while: I'm someone who spends almost no waking time at home and I [[file:huel.org][don't need a kitchen to cook or store food]]. 
On top of that, I have always disliked the idea of believing things are /essential/ just because society has agreed upon it. Not everyone wants to own "space", and while I do see some value in it, I believe what I pay in rent has often exceeded the value I get from an apartment. 
In an ideal world, I'd love to be able to lease a bed in a capsule hotel/hostel style building long-term for the added safety + climate control, but a car seems like the closest thing actually available.

Obviously, there are complications, which is most of why I haven't committed to car living long term yet.
Not having a permanent address in IL could cause some issues with the government, and IL winters are cold enough I'm worried sleeping in an unheated car could have risks (even with a properly rated sleeping bag).
But for 2 weeks during the summer when it's warm and campus is quiet, what could really go wrong?
Sleeping in your car is entirely legal where I live as long as you don't park in a metered spot or on private property. Urbana in particular has plenty of relatively secluded street parking.

In the coming summers, I plan to intern off campus, and saving 3 months rent in a high CoL area is enticing, so long as I know in advance that car-camping won't severly impact my quality of life. This year's lease gap was the perfect time for a trial run!

* The Before
** Preparation
- Hard to decide what I would / wouldn't need, probably overpacked clothes
- I do BJJ so I needed my Gis which would take up lots of space. Also was a bit worried about smell of used gym clothes
- Bought covers for windows, cleaned car interior
- 4 bags: BJJ gym duffel, work backpack, toiletries backpack (held all toiletries to not look conspicuous in crunch), small suitcase of clothes
- put yoga mat on flattened seat and brought bedsheets
  
** The Plan
- bathroom at office, 24/7 access to many school buildings
- morning gym for lifting (already do this) + shower there and brush teeth
- afternoon gym (BJJ) then shower (again) + evening routing (easy bc women's restroom is usually empty)
- on weekends, shower once (after lifting) and brush teeth in a school building or coffee shop restroom
  
* During
** Day 1
- After evening gym sesh went to work/study for a bit on campus, brushed teeth there
- Wasn't stressed well in advance, but definitely felt a bit on edge trying to fall asleep. Window covers weren't perfect, so if someone tried they could see in
- Originally only cracked the windows very slightly and it got HOT -> had to go back and crack more, probably should've gone even further
  - Was scared of bugs + felt weird hearing things / ppl walking by. Also just don't like being exposed ot the outside
- Took a while to fall asleep but once asleep it was fine
- Woke up to my alarm at 5:40am, was already bright outside, drove to gym and all was good
- Luckily no issues w/ needing a bathroom :skull: -> but also pretty sure I was dehydrated after gym
  
** Days 2, 3
- Went to CA, no car sleeping
  
** Day 4
- drove back from airport (~2 hours), was exhausted
  - slept super easily
- Gym closes sunday night so no shower, just used restroom on campus and then went to park
- left front windows halfway open, no issue w/ fogging up / getting too hot
  
** Days 5-9
*** Day
- Didn't sleep great, really really tired afterwards
*** Day 6
- Parked in a different spot b/c I had spent 2 in a row same spot, was a bit nervous bc didn't know the area / change
- Less street lights tho (also I think maybe I was behind a van someone was living out of??) -> related note, I could 1000% live in a van full time, it would solve all my problems (space, privacy)
*** Day 7
- Gym in morning
- Gym again in evening -> went to my friend's muay thai gym bc I've been considering cross-training (my mma gym has muay thai but it's almost always sparring no technique) -> they had no shower :sob:
  - had to go back to crunch late at night, do some cardio / abs to not be suspicious, and then go find somewhere to sleep
- Awful sleep -> super hot (was still high 70s at 2am) and I had to pee twice (midnight at gas station, 2am on campus) + was dehydrated. 
  - Only ended up getting 3 hours solid sleep according ot my watch
  - Very frustrated
- also started to notice bug bites
*** Day 8
- today was awful, so tired, couldn't do anything
- gave up and booked a hotel, slept 5pm - 9am, skipped gym + everything else I needed to do
*** Day 9
- Picked up a blood sugar monitor, wasn't sure how temp sensitive so keeping in office (been having low blood sugar scares)
- went to my MMA gym in the evening (BJJ + women's class) -> showered there but clothes were too sweaty to leave, had to go do laundry (my friend gave me quarters)
  
** Nights 10 + 11
*** Day 10
- the weekend
- bbq 10-5, got soooo sweaty (but also was fun)
- slept in lab
*** Day 11
- slept in lab, someone came to work at 11pm tho
  
** Nights 12-15
*** Day 12
- Went to MMA gym for BJJ then Vonnora Muay Thai (back to back) ? -> maybe not doable
- slept in lab, someone was working until 1am tho, I slept on other side of room to give him space but not ideal, felt bad
*** Day 13
- TIRED again, gym was rough in the morning, didn't go in the evening
- gave up and booked a hotel
- also it was rainign
- and 90 degrees
*** Day 14
- Muay thai again -> side not really like the gym + the kru there
- no morning gym (12 hours of sleep)
*** Day 15
- last night thank god!
 
* Reflections
- most important question: would I do it again / would it be sustainable for longer
- what is most difficult
  - storing stuff -> was worried about stuff getting moldy / damaged in car, shampoo kept exploding in the heat
  - If I were to do long term, would invest in storage thing for top of car, get sweaty clothes + shoes isolated
- unfortunately was during a heat wave: didn't get below 74 at night some nights, 100+ during the day
- excercising at night causes problems bc dehydration + having to pee due to water consumption, also I work out hard enough during MMA to get nauseous, sometimes puke
- started eating really badly bc of stress, stress hives, swollen lymph nodes
  - having blood sugar issues so that's not good


* TODOs for me
- had to interview a postdoc canidate in opposite time zone -> had to be up late (kms) w/ no ability to sleep in. 
