#+title: Huel
#+subtitle: "lakdf" -- soylent green maybe? 

* What is Huel? 
Huel is a meal replacement drink. 

* My Experience
I've been on Huel for ~2 years now...

Very convinent, specifically better cold, which reduces convinience b/c then you need a fridge
Eat high protien version -> lack of carbs is a problem. Have some blood sugar issues and Huel can't solve them bc of this, usually I eat oatmeal for carbs but causes me to resort to candy sometimes

Very filling to drink, so hard to consume many calories fast -> this is bc of water content. Also I use a much higher ratio of water to powder than recommended, further exasparating that

Bars are not calorically dense enough

* Discussion
- But won't you miss normal food? -> if you miss normal food, eat normal food. I'm not saying to give it up entirely. For me, going out to eat with friends on occasion is enough to satisfy those cravings. When you get to a meal, you will always have the /choice/ to cook, or pick a fast meal of Huel. If you don't miss normal food enough to pick cooking, then Huel is improving your life.
