#+title: Huel
#+subtitle: "lakdf" -- soylent green maybe? 

* What is Huel? 
Huel is a meal replacement drink. 

* My Experience
I've been on Huel for ~2 years now, with it making up ~25-100% of my diet based on the time period.

Very convinent, specifically better cold, which reduces convinience b/c then you need a fridge
Eat high protien version -> lack of carbs is a problem. Have some blood sugar issues and Huel can't solve them bc of this, usually I eat oatmeal for carbs but causes me to resort to candy sometimes
Very filling to drink, so hard to consume many calories fast -> this is bc of water content. Also I use a much higher ratio of water to powder than recommended, further exasparating that
Bars are not calorically dense enough

One question I always ask when talking about Huel to friends is: "But don't you miss normal food?". I find this to be such an odd question, because most people don't eat "real" food for every meal. People snack, they eat ramen and fast-food, they skip meals entirely, or they have a protein bar. Huel is meant to replace these instances, and make it easier to get a nutritious meal when you don't have the time or willpower to cook. If you miss normal food, then eat normal food. For me, I find that going out to eat once in a while can be enough to satisfy my craving for "real" food. More recently, I've been cooking a bit on the weekends as well. But during the week when I don't /want/ to think about food, Huel is an invaluable tool for keeping myself healthy.
