#+title: Huel
#+subtitle: "You've gotta tell them! Soylent Green is people! We've gotta stop them somehow!" -- Soylent Green (1973)

Link: [[https://huel.com][https://huel.com]] 

* What is Huel? 
Huel (Human Fuel) is a meal replacement company that aims "to make nutritionally complete, convenient, affordable food, with minimal impact on animals and the environment". All Huel products are vegan, and many are gluten-free.
The main Huel offering is their meal powder, which comes in high-carb, standard, and high-protein varients, and can be mixed with water for an instant meal. However, they're constantly expanding their product offerings, which now include rehydratable hot meals (think MREs), protein bars, greens powders, and more.
I do not enjoy cooking, and I also dislike eating out (due to the cost, time commitment, and poor nutrition of restaurant food). Therefore, I was enticed by the idea of a relatively cheap way to eat high protein with /no/ cooking required, and without being worried about nutrient deficiencies. 

* My Experience
I've been a Hueligan (Huel customer) since 2023, with it making up ~25-100% of my diet at any given point in time.
I find it incredibly convenient, especially when working in the office, where I keep a few bags at my desk and mix up a bottle whenever needed.
Due to the high water and fiber content, a bottle of Huel is very filling to drink (I use a higher-than-recommended ratio of water to powder, which exacerbates this).

Of their product line-up, I've tried the powder, the rehydratable meals (packets and cups), the protein bars, the greens powder, and the energy drinks.
While nice tasting, I don't buy the greens powder or energy drinks regularly since I don't have much of a use case (see [[file:zest_caffine_pills.org][here]] for how I prefer to consume caffeine).
I do keep protein bars on hand and in my bag, but they're more of a "for emergencies" type purchase than something I eat every day. I like the convenience, but wish they were more calorically dense than they are. 
The rehydrateable meals are great but more expensive and lower in protein than the powder, so I tend to eat them only a few times per week, mostly as a way to satiate any cravings for "real food" when I'm not keeping any groceries at home. 
The high protein (black edition) powder is my go-to. I cycle between flavors for variety, but always keep a few bags at home and in the office. In terms of convenience, price, and nutrition, the product is unmatched.

** How it works with a High Metabolism
Huel's nutrient content is designed to be sufficient assuming a 2000-calorie diet. I have a high metabolism and work out frequently, so I need well over 2000 calories a day to stay healthy. 
While Huel is cheaper than many other protein sources for the same calories/macros, it's expensive enough that I'd prefer to fill out the extra calories with something else, and I don't find it worth buying the high-carb version.
Luckily, 2000 calories of Huel black powder is already 200g of protein (more than enough), so I consume cheap energy sources such as rice, oatmeal, and/or peanut butter to up my caloric intake cheaply.
I've also found Huel to be much to low in electrolytes and does not contain creatine, but this is easily correctable using supplements.

* Discussion
One question I always ask when talking about Huel to friends is: "But don't you miss normal food?". I find this to be such an odd question, because most people don't eat "real" food for every meal. People snack, they eat ramen and fast food, they skip meals entirely, or they have a protein bar. Huel is meant to replace these instances and make it easier to get a nutritious meal when you don't have the time or willpower to cook. If you miss normal food, then eat normal food. For me, I find that going out to eat once in a while can be enough to satisfy my craving for "real" food. More recently, I've been cooking a bit on the weekends as well. But during the week when I don't /want/ to think about food, Huel is an invaluable tool for keeping myself healthy.

Many people seem afraid they will somehow lose the ability to digest normal food if they drink too much Huel, or that it's not actually healthy. Luckily, the Huel website is very open about nutritional information, ingredients, and testing. They provided data and studies showing that Huel is good for you: participants consuming only Huel saw health improvements. The protein /does/ get absorbed at a similar rate to protein from meat sources. All essential amino acids are present in a healthy ratio (etc, etc). 

