#+title: Zest Labs Wake-Up Pill
#+subtitle: "beggars in spain quote" -- Nancy Kress, Beggars in Spain

Link: [[https://takezest.com/product/wake-up-pill][https://takezest.com]]

* The Product
You can read their website,but I'll summarize

One issue I face in day to day life -> getting out of bed is hard. I schedule morning gym sesh / try to be in the office early, but it's easy for me to choose sleep instead, or, just have trouble getting up. Want to "feel" well rested even when not.

* My Experience
** First Attempt
The first time I took Zest, despite their warnings, I ate a large meal (chipotle) an hour beforehand. I took the pill at 10pm and work up at ~4am with my heart pounding. 
- was pretty suprised the caffine was so "potent" -> only 80mg
** Second Attempt 
Didn't eat beforehand, took just after 10pm, woke up just before 6am.
Not convinced it's exactly 8 hours, a bit less for me, but I'm fine with that, as I don't really get 8 hours of sleep consistently (nor should you be taking the pill imo if you will)
** The Pill as a Jetlag Cure
Went to CA and got sick, was struggling to get back on Central Time (waking up @ 9 and still tired).
Took the pill -> woke up at 6am and made it to the gym
** Side Effects
Being excited to use the pill but seeing that it was only 80mg caffine drove me to cut coffee / energy drink consumption after my purchase. I wanted the full effects and was concerned caffine tolerance could mess with it. (positive side effect for my wallet lol)

* Discussion
Some ppl say "not fixing symptoms, just hiding them". Obviously, yes this is the case. I'd love if there was a pill you could take to not need sleep at all (or gen-mod... beggars in spain ??), but we're not there yet. The thing is, I have enough I want to do while awake that I was never going to get more sleep. The choice is between being tired and feeling tired or being tired and feeling great.

Not magic. It is possible to go back to sleep after waking up, find that it is less effictive when sleeping next to my boyfriend (bc I'll want to cuddle before getting out of bed and fall back asleep).
