#+title: Superman (2025)

- public reception: very leftist / radical? ok but superheros /are/ inherently left wing. The idea of vigalante justice (i.e. non gov) is that the gov doesn't do enough to protect people who need/deserve it. Superheros have always been there to protect ppl getting fucked over by traditional justice / law enforcement. 
  - yeah some work w/ the gov, but what superhero has ever not disagreed with them?
  - NVM after watching it was blatent commentary on what's happening in israel and the gov, very "left wing" in terms of denouncing israel / supporting Gaza, but also appaerently overall US sentiment is shifting that way, so...
    
- Really liked "supergirl" cameo at the end, now I'm looking forward to that movie. Vibe was "female superhero who does not take things seriously" -> think deadpool vibes, and idk I really think that's good rep? 
- Lois and Clark's relationship was not #goals like tiktok led me to believe -> interview scene was kinda cute (like tbh probably not healthy but it reminded me of my bf) and they barely interacted the rest of the movie? idk they just did not seem right for each other
- some of the humour was too juvenille in my opinion, but whatever (especially w the dog)
- It was a good movie, I feel like James Gunn tends to like doing movies/tv with imperfect heroes, so it's interesting that he did superman, bc superman is perfect / unflawed
  - But also he kinda showed that superman had flaws, not emotionally mature, didn't think things through, "too kind"
- Lex Luther was based, actually had a lot of empathy for him, not necessarily rooting against him
  - Like yes he was bad and doing bad things, but also he's just so impressive while doing it. I think he was good "evil mastermind" rep. bc it was so realistic to how an evil mastermind would have to behave in today -- like it could totally work (and tbh probably does, ... republican party starting culture war to get the poor to support the rich)

On a related note -- the GQ photoshoot starring David Corswet is some of the best male styling I've seen. 
- inspired to go buy + embroider a jean jacket... 
- todo insert image
