#+title: Beggars in Spain
#+subtitle: "But never before in the United States had the objects of envy and the objects of biological prejudice been the same group.” -- Nancy Kress, Beggars in Spain

"Beggars in Spain" tracks the reaction of society to advanced genetic modification techniques: specifically a small group of individuals modified to not require sleep. As a result, these "sleepless" have twice the amount of time in the day, and develop mentally at a much faster rate than their peers. Beggars in Spain tracks the lives of the sleepless from birth to death and imagines what such a life would be.
We get to understand how sleeplessness affects and alienates our characters internally, and watch as greater society turns to alienate them once they realize the magnitude of an advantage the sleepless have in economic productivity.
We watch the slow rise of both social and systemic discrimination, with the sleepless eventually becoming the most hated subgroup of American society despite also being the most successful.

We then get to watch as the sleepless grapple with defining their own moral and ethical principles -- what do they owe a set of people who not only hate them, but also have nothing of value to offer?
As economic productivity increases due to advanced technologies, profits become more concentrated in sleeper communities due to their monopoly on corporate leadership positions. The U.S. is forced to become, in essence, a welfare state due to the lack of jobs; and yet the only ones able to pay enough taxes to fund the switch are the few people who /are/ working (the sleepless).
Recent advanges in agentic AI make such a future scarily realistic, and the author poses many relevant, interesting questions about the future of society.

"Beggars in Spain" was by far one of the best books I've ever read, tracking the epic rise and fall of a turning-point generation. I would recommend this book to anyone interested in speculative fiction, but especially those who've found themselves pondering how AI-enabled economic productivity will affect us in the long run.

