#+title: Red Mars
#+subtitle: "History was like some vast thing that was always over the tight horizon, invisible except in its effects. It was what happened when you weren't looking." -- Kim Stanley Robinson, Red Mars

I read this for a bookclub, and in all honesty, got quite bored. I'm not convinced I would have finished if reading on my own. 
This book is follows a group of well respected individuals from various fields and countries sent to begin the colonization of mars. It's definitely an interesting premise, and the author puts a lot of effort into imagining what such efforts would really look like, but as a result, the story moves quite slowly, and the efforts are quite mundane. 

I did really enjoy the POV shifts; each part of the story was told from a different point of view, and the characterization of certain actors/actions was wildly different based on the character who's eyes we were currently seeing through. It was pretty fun to find out that our understanding of certain things was colored by human pettiness at times.
