#+title: Service Model
#+subtitle: "The hypothetical occurred to him: If it were me, and my tasks were definitively fulfilled, would I walk into the fire? And the answer, If I were told to, surely yes" -- Adrien Tchaikovsky

# Are you there, God, he replied. It is me, Uncharles.
# God, he sent, I have decided not to accept the position here

This book follows a robot valet named Uncharles after he is forced to leave the household he was programmed to serve due to his faulty behavior (which led to the accidental murder of his employer). As Uncharles searches for a new human master to whom he may be of service, we are repeatedly asked to question his motives and grapple with whether or not Uncharles has gained any sort of conciousness or free will.
I think this book adopts an interesting lense with which to look at the question of sentient AI through an interesting lens due to the subtletly of Uncharles's awakening. The story is written in 3rd person, but we are made aware of Uncharles's "thoughts" and "feelings" throughout. Despite being robotic, sometimes to a comical extent, I found Uncharles relatable yet far from human. 

While travelling in search of employment, Uncharles is navigating a wasteland of human civilization, and we come to learn that most humans have died out, at least in part due to the introduction of sophisticated robots and AI technology. The author imagines this societal decline in a way that seems scarily realistic. Uncharles is completely uninformed about this disarray, despite having served a human up until only a few days prior, likely because his wealthy human master had simply stopped engaging with society once it began to struggle. We're told explicitly that over half of society did not believe in the fall of humanity due to their consumption of only "carefully curated news sources", something already difficult to avoid as social media increasingly becomes a place where people share their un-nuanced interpretations of current events.

This book is sectioned into 5 parts, each loosley inspired by another author, with pretty significant shifts in tone and style between each part. I found this to be quite fun, and I really enjoyed the subtle and not-so-subtle references. The final part, inspired by Dante, was my favorite, as I found the religious imagery and creation of a computerized "God" to be both amusing and thought-provoking when set against the robot-wasteland backdrop. 

Overall I really enjoyed this book and would highly recommend.

