#+title: Some Desperate Glory
#+subtitle: “Proving you were capable of saving the world didn’t mean you could, or that anyone would let you.” -- Emily Tesh, Some Desperate Glory

I orginially picked up this book due to it being awarded the Hugo for best novel in 2024 (well deserved). 
Originally I was uncertain if I'd like it, as for some reason the advertising and reviews of this book seem to be quite inaccurate descriptions of the book itself. Its goodreads page decribes it as a "queer space opera", and while there are quite a few queer characters, any romance ends up being only a minor portion of the story. There were also quite a few reviews calling the main character "problematic" and "bigotted", which, while true to an extent, was quite obviously a deliberate choice on the author's part to reflect how Val was affected by her upbringing and limited interactions with the world outside her station.
Once I started reading, I found myself enjoying maybe /the best/ execution of an unreliable narrator I've seen in a novel. We learn about Val's world and its history/politics in the limited context of what she has been taught, and are just as shocked as her when we realized what we've learned is, in many cases, wrong.
Contrary to the reviews, I found most of the characters fun and relatable. Their obvious flaws only served to humanize them, and make me more empathetic to their situation.
While the ending of the novel was a bit dissapointing, the experience of reading was definitely worthwhile.
