#+title: The Mountain in the Sea
#+subtitle: “The great and terrible thing about humankind is simply this: we will always do what we are capable of.” -- Ray Nayler, The Mountain in the Sea
This book is definitely not what I expected based on the jacket summary, but I cannot say I was dissapointed. While the story claims to be about a colony of octopi that have managed to develop a culture and language of their own, the story ends with us gaining very little understanding of what that entails.
In fact, we as readers never learn more about the octopi than the scientists studying them are able to observe. I actually really liked this about the story, as I think it mirrors real scientific research quite well: progress is slow and major results are unlikely within a single person's career/lifetime, but that does not make study worthless.

More interesting than the octopi is the world in which they are being studied. The setting is a version of earth (far?) in the future where AI has become indistinguishable (in some cases) from human life. We are shown various AI entities (an AI run slave ship, animatronic AI monks, AI significant others) which have varying levels of sentience based on the tasks they're given. It felt as if the author was asking us to try and draw the line as to which we'd consider sentient (if any) and which we wouldn't, which is actually quite difficult.
I will admit I was a bit dissapointed with how many answers the author tried to "give" us directly to questions that were, in my opinion, much too philisophical in nature to have correct answers. Luckily this was a pretty minor inclusion and didn't affect my overall enjoyment of the book.

Especially now as AI gets more advanced and becomes an essential part of life, this book hits close to home. Definitely one I'd recommend.

