#+title: The Three Body Problem
#+subtitle: “To effectively contain a civilization’s development and disarm it across such a long span of time, there is only one way: kill its science.” -- Cixin Liu, The Three Body Problem

Wow, I loved this. This series tells the story of a much more advanced alien society coming to colonize Earth due to climate issues which are devestating their own planet and societies. But the universe is huge, and these aliens are coming from far away, giving Earth hundreds of years to prepare. The most fascinating part of this book was the politics: watching Earthen countries come together to try and address a huge, almost impossible threat which /technically/ would not affect the ones currently solving it. After all, the arival date was set farther in the future than a human would be expected to live. The series has some great moments, from video game propaganda to massive gambles based on the insanity of a single person. The writing itself was also phenomenal, and I found myself being forced to ponder exactly the questions the author wanted, then shocked at the answers.
